### ISSUE TITLE
RPC calls not working

### ISSUE THREAD

**Issue by enterovipunen** [DogeChia/doge-chia#1]
(venv) root@virtualserver01:~/doge-chia# dogechia netspace
Exception 404, message='Not Found', url=URL('https://localhost:6769/get_blockchain_state')

(venv) root@virtualserver01:~/doge-chia# dogechia farm summary
Exception from 'wallet' {'error': "'NoneType' object has no attribute 'tx_store'", 'success': False}
Exception from 'full node' 404, message='Not Found', url=URL('https://localhost:6769/get_blockchain_state')
Farming status: Not available
Total dogechia farmed: Unknown
User transaction fees: Unknown
Block rewards: Unknown
Last height farmed: Unknown
Plot count: 0
Total size of plots: 0.000 GiB
Estimated network space: Unknown
Expected time to win: Unknown
Note: log into your key using 'dogechia wallet show' to see rewards for each key

**Comment by Ilmairinen** [comment]
Issue resolved
