### ISSUE TITLE
start_wallet.exe taking a lot of CPU

### ISSUE THREAD

**Issue by naymecliff** [DogeChia/doge-chia#11]
**Describe the bug**
While running the windows GUI, I found that even after syncing, it consumes a lot of CPU. I checked it in the task manager and hunted it down to the start_wallet.exe. It constantly takes 8-13% of the CPU.

**To Reproduce**
Start the GUI, check in in the task manager

**Expected behavior**
start_wallet should only take 0 to 3%, mostly 0. Like the original Chia wallet

**Comment by Ilmairinen** [comment]
Hello @naymecliff  - What version of DogeChia are you running? Are you still seeing this excessive CPU behavior? Did you install windows binary or from source? - I am having difficulty reproducing your issue. Any additional information would be most helpful. Thanks.
