### ISSUE TITLE
Support of new “Portable” NFT ploters

### ISSUE THREAD

**Issue by arturotrenard** [DogeChia/doge-chia#19]
Hello on the Chia Forks page they indicate that it has full support for the new NFT plots but it is not like that. I have two weeks already harvesting and I only receive 25% of the reward. So my question to you would be. When do you start incorporating full support for the new NFT ploters? Thanks a lot

**Comment by Ratzoletto** [comment]
Same Problem here...

**Comment by ldsxp** [comment]
Same Problem here...

**Comment by jxyjest** [comment]
Same problem

**Comment by bkdnk** [comment]
20days and nothing, I recive just 0.25XDG per 1 block, when and how I can receve 1.75? Thanks
