### ISSUE TITLE
The app tries to connect to chia chain !

### ISSUE THREAD

**Issue by xludodx** [DogeChia/doge-chia#6]
0xf35d4142a87844b76ff9f13d95c10dd56e24505c73fea3dc493cc144f6941ccd
220.253.127.115
8444/8444
0/0
Full Node
388,996
0x32ed6b329f4ca06cfa4c4e2b2d70582d8f681cfc2dfaca78dd5811eb09ef0889
174.71.21.171
8444/8444
0/0.1
Full Node
560,949
0xc850fe7fc29f8d001ea10f93b894b32a88c6979aad5d1338b7385636e108506c
24.252.159.74
8444/8444
0/0.2
Full Node
560,949

**Comment by xludodx** [comment]
false positive

**Comment by ageorge95** [comment]
It is not a FP. I happens now as well. It tries to sync-up from Official chia nodes at port 8444 !
